### ISSUE TITLE
Paste second (and following) images with the number/index added

### ISSUE THREAD

**Issue by woojiq** [typst/webapp-issues#168]
### Description

_Thank you for this product. It's just a pleasure to do university homework in typst webapp._

When you insert the first image it is called "image.png", when you insert the second you have two options: overwrite the original or skip it. I would like to have a third option or just replace the overwrite option (imo, overwriting is very rarely the desired behavior). The third option - _"name new image with appended number/index"._ For example, "image2.png" or "image-2.png".

### Use Case

Pasting many small images from the clipboard that do not need to be renamed.

**Comment by pklaschka** [comment]
I agree that this is annoying, but think that just adding numbers will get messy super quickly. Instead, I would like to suggest an alternative UX flow, allowing to specify a descriptive name, that looks like this:

**Proposed workflow**
1. paste the image
2. a popup opens, asking for the file name. The name defaults to `image.png` or, if this already exists, `image2.png`, as suggested in the PR description. The file name (without the extension) is initially highlighted to allow quick overrides.
3. After keeping the name or entering a new name and pressing the return key (or clicking an "Ok" button), there are two scenarios:
   1. A file with that name already exists. In this case, show options to override or go back to the name selection
   2. Otherwise, insert that name
4. The image gets inserted with a correct link.

**Additional specifications**
- A `/` can be used to place the image in a subfolder. For example, entering `images/a.png` as the name results in the image getting placed in a folder called `images`. The folder gets created if it doesn't exist.
- If the upload actions are triggered in a subfolder, paths in the file name get resolved relative to that folder.

**Comment by knarkzel** [comment]
Preferably just use uuid or some kind of hash.

**Comment by pklaschka** [comment]
> Preferably just use uuid or some kind of hash.

I _think_ I disagree here. With `image.png`, `image2.png`, etc., there is at least a bit of semantic information for those who don't want to give their images better names (i.e., the order of uploads). If you have something like a letter with two figures/images, that might just be enough semantic information to recognize them. That, however, wouldn't be the case with hashes or something like that.

**Comment by laurmaedje** [comment]
I think a popup that asks you to enter the name would be the most useful.

**Comment by ecstrema** [comment]
> I think a popup that asks you to enter the name would be the most useful.

I don't think so. In WYSIWYG editors, you don't ever have to think about how to name you images, and that's a good thing. I don't want to spend time naming things that don't need a name.

**Comment by pklaschka** [comment]
> > I think a popup that asks you to enter the name would be the most useful.
> 
> 
> 
> I don't think so. In WYSIWYG editors, you don't ever have to think about how to name you images, and that's a good thing. I don't want to spend time naming things that don't need a name.

@ecstrema Please don't take this the wrong way -- I'm honestly just curious (this is a matter of preference, after all, and I'm not here to argue about preferences):

So you would prefer it if there are a bunch of essentially unnamed image files in your project (and when editing it later, you basically have no idea which is which except by looking at it)?

With the popup, you could still, if that were the case, press enter without thinking about it, by the way (which would quickly become muscle memory).

I'm honestly just curious because to me, that sounds like a total mess to work with. For a letter with two images, maybe. But for a paper/longer document, which you work on for longer than ~ 2 hours, having totally unnamed files honestly sounds horrific to me 🤔
