### ISSUE TITLE
Nav drawer dropdowns are broken

### ISSUE THREAD

**Issue by mattfbacon** [typst/webapp-issues#202]
### Description

This seems like a similar issue to typst/webapp-issues#110. In the nav bar, open dropdowns don't actually show their content, and they can't be clicked on.

![Demonstration](https://github.com/typst/typst/assets/58113890/f841de92-b486-4127-92ac-7a121a6c4057)

This demonstration was made using Firefox with responsive design mode enabled in Dev tools, but I have reproduced it in Firefox for Android as well.

### Browsers

Firefox

### OS

Linux, Android

**Comment by reknih** [comment]
Are you still experiencing this issue? I cannot reproduce it in Firefox 121.

**Comment by mattfbacon** [comment]
Yes, I can still reproduce it.

![The "Reference" dropdown open with no visible content, just a white space where its subitems would be](https://github.com/typst/webapp-issues/assets/58113890/81545d59-b112-48f7-90bf-e09958744886)

**Comment by laurmaedje** [comment]
Still can't reproduce this and haven't heard from anybody else having this. From the image it also looks like the font isn't loading correctly. Maybe something else was blocked as well?

**Comment by mattfbacon** [comment]
I still have the problem. I mean, it's pretty obvious, the content `ul` has `opacity: 0` even after opening

![Content under "Reference" dropdown in sidebar is still invisible](https://github.com/user-attachments/assets/a4976576-a620-4a8f-89ea-32345fa20d22)

![The HTML for the opened "Reference" dropdown shows that `opacity: 0` is set on the content `ul`](https://github.com/user-attachments/assets/c2ee3db0-4f87-41e2-9f6f-35e674d4e9a4)

The fonts thing is unrelated.

In Chromium the opacity is 1 when opened and it works properly. Seems like some finnicky/non standards-compliant JS. I would suggest to just write some simple CSS as described in #110 (btw, the examples dropdowns work fine after you changed them to use `details`/`summary`) that uses the `aria-expanded` attribute to control the `opacity` of the content `ul`.

**Comment by mattfbacon** [comment]
For future reference I have fixed this on my side with this user CSS:

```css
nav li[aria-expanded=true] > ul {
    pointer-events: auto !important;
    opacity: 1 !important;
    user-select: auto !important;
}
```

**Comment by jbirnick** [comment]
I have the same issue. I have it on my (Linux) Laptop and on my two (Android) mobile phones, no matter which browser I try. The only _working_ setup I can produce is with the Tor Browser.

Meanwhile everyone else tells me it works for them.. it's very weird because other people with Firefox 135 tell me it works for them, but with my Firefox 135 it doesn't work.

**Comment by jbirnick** [comment]
Here is a YouTube video showing how the Javascript executes differently in both cases:
https://youtu.be/rqcu3y17d-w

**Comment by jbirnick** [comment]
Looks like the variable `G` is `true` in Firefox (where it doesn't work) and `(unavailable)` in Tor (where it works).

@laurmaedje Could you perhaps host the docs somewhere without minifying the JS so I can trace it down?

EDIT: Here is the difference:
![Image](https://github.com/user-attachments/assets/3483a4d2-2ff5-491d-a1b2-1d77b0f14cc6)
There is this check where it either executes the sequence of commands that set some style properties or it executes `n()`. Looks like when it works, the former is executed. When it doesn't work, `n()` is executed.

**Comment by mattfbacon** [comment]
I find this investigation interesting but it would be much easier to just use CSS as described above.

**Comment by laurmaedje** [comment]
With CSS it's not possible to animate it like it's currently animated

**Comment by jbirnick** [comment]
@laurmaedje I have found the issue. At some point you set a variable to this value:
```js
window.matchMedia('(prefers-reduced-motion: reduce)').matches
```
This essentially asks if animations are desired or so. But then in the relevant code for the drawer, you apparently don't use it correctly. If animations are disabled then you also don't set the opacity and so on. (And also it looks like this media query could return `undefined` or something, though I'm not sure.)

(It is the variable `G` above. See how you skip all the commands for setting the style.)

Indeed, I tested that when I change my desktop environment to one where animations are enabled, then it works. And that it doesn't work on my and @mattfbacon mobile phones is probably because we have disabled animations on them.

**Comment by mattfbacon** [comment]
Correct, I also have animations disabled.

**Comment by mattfbacon** [comment]
By the way, it is possible with CSS, you just need a little bit of JS to get the `clientHeight` and store it in a CSS variable that can then be used as a fixed maximum height for the animation. But since we are already using JS for this it's irrelevant.

**Comment by laurmaedje** [comment]
@jbirnick Thanks for the investigation! We'll implement a fix.

**Comment by laurmaedje** [comment]
I pushed a fix, will take half an hour or so until it's live.
