### ISSUE TITLE
Rename project in dashboard

### ISSUE THREAD

**Issue by zouharvi** [typst/webapp-issues#28]
### Description

It took me a while to find out how to rename a project (open settings in editor mode).

![image](https://user-images.githubusercontent.com/7661193/234857348-04717173-e9b0-4c04-9535-f89bff6988ea.png) ![image](https://user-images.githubusercontent.com/7661193/234857428-384ea457-3fe8-4d3f-b141-de40fe4f8adc.png)

Having this in the dashboard among possible actions would make it easier to organize but (afaik) that is not possible.

![image](https://user-images.githubusercontent.com/7661193/234857645-c7fee85f-9df7-41da-93f5-67d512bc0819.png)

### Use Case

Overleaf also doesn't have this feature in the project overview page and one needs to open the project in order to rename it. However, this makes organization of larger number of projects cumbersome (imagine having to open a file in order to rename it).

![image](https://user-images.githubusercontent.com/7661193/234857861-ae8548c7-0cbc-4124-9aa6-7db89f897e7e.png)

**Comment by Andrew15-5** [comment]
Wow! I can actually change editor's font? And it also supports ligatures? Nice!
![image](https://github.com/typst/webapp-issues/assets/37143421/bd612929-aa26-4526-8c89-10cb0f7bdcde)

I must say, opening unchangeable settings button in a project feels wrong.
![image](https://github.com/typst/webapp-issues/assets/37143421/3f67ffd1-0ffc-4583-a397-8f8c2ec7108a)
Or at least I wish there was a difference in how it looks. Because I assumed that if the button is the same at all times, then it means that I will access the same settings at any point in the app, so I didn't even bother trying clicking on it. Maybe adding an explicit "Project properties" menu item to "**Typst**"/"File"/"Edit" menu will be good (all editors have that, e.g., LibreOffice Writer). And having these settings for project-scoped settings seems like a bad idea (are they global?). I want to have the same font family and size for all of my projects, so these settings should rather be in main/global settings.
![image](https://github.com/typst/webapp-issues/assets/37143421/c58f92b6-c029-41df-a797-3fe3913582fe)

And I would like to have settings be automatically saved (name/owner/compiler; you rarely see "save" buttons nowadays):
![image](https://github.com/typst/webapp-issues/assets/37143421/08d036c3-5552-47f2-8509-1c02ba34334b)


I also know that major text processors that have project/file's name in the UI have an ability to click on it and edit it in-place, but Typst only has a read-only name:
![image](https://github.com/typst/webapp-issues/assets/37143421/663e99af-0eda-40c6-bc4c-cee12cf34156)

**Comment by reknih** [comment]
We'll add an overflow option that opens a context menu on the dashboard. The menu will contain the rename action, and the clicking it should open a modal with a rename input field.
