### ISSUE TITLE
Bugs in folder creation

### ISSUE THREAD

**Issue by martinosorb** [typst/webapp-issues#288]
### Description

Two issues:

1.  Clicking the new folder button always  creates a folder within another folder, even if no folder is selected, instead of creating it in the root of the project.
2.  If I drag a folder, and I inadvertently drop it on itself, it creates a folder within it, with the same name, and all the contents are moved into the subfolder.

### Browsers

Firefox

### OS

Linux

**Comment by reknih** [comment]
Hey, we just marked this as closed because we fixed that folders can be dragged on themselves. I was not able to reproduce your first issue, although the current behavior may not be the most intuitive: You can create a file at the root after clicking on another file in the root, otherwise, it will be created in a folder.

**Comment by martinosorb** [comment]
I see what you mean. I tried, and, as you say, the way to create a folder in the root directory is to select a file in the root directory. My expected behaviour would be that if I click in the empty area below the files listing, it would also "select" the root directory. As it is now, it does not. The behavior is counterintuitive because all folders are closed, none of them is *visibly* selected, and yet they are still "selected" for the purpose of where the folder gets created. Not sure if it's clear, let me know if I can explain it better. Thanks for the reply.
