### ISSUE TITLE
Bad matching of categories when exploring packages

### ISSUE THREAD

**Issue by max397574** [typst/webapp-issues#313]
### Description

it seems like a package has to contain all the selected categories here 
so e.g. if I disselect scripting, office, poster or presentation codly goes away
assuming these are the categories under which codly falls I'd expect it to show up when any of those are selected not just when all are selected

this also has the side effect that when just a single category is selected really few or for most categories no packages at all show up
![image](https://github.com/typst/webapp-issues/assets/81827001/a8a178cf-53b6-4631-952e-442b7188c090)

### Reproduction URL

https://typst.app/universe/search?kind=packages&featured=false

### Browsers

Safari

### OS

macOS

**Comment by JuanM04** [comment]
Hi, sorry for the late response. I've checked out codly and the issue is that the package doesn't have any categories. Below is a screenshot of [curryst 0.2.0](https://typst.app/universe/package/curryst/0.2.0), which has multiple categories. You'll notice that codly doesn't have any of these in its Universe page.

![image](https://github.com/typst/webapp-issues/assets/16712703/0e6fc752-18e3-402f-ba13-a40e20b6d390)

The reason why codly disappears is that we have a special condition in place: when all categories are selected, we assume that the user wants to see _all_ the packages, regardless of their category. If you think that codly fits in some of the categories that you mentioned, you can open an issue or pull request in [their repository](https://github.com/Dherse/codly) so it gets filtered correctly 😄
