### ISSUE TITLE
Error on all file creations: _"The file name already exists in the project"_

### ISSUE THREAD

**Issue by zouharvi** [typst/webapp-issues#325]
### Description

Whenever I create a new file, I get the error that the file name already exists, even in a new blank document. Despite the error message, the file does get created. Happens on all file creation but renaming is fine.

**Reproduction:**

<img src="https://github.com/typst/webapp-issues/assets/7661193/b56c5671-4cb5-499c-8b76-1d30694fe686" width="200px">
<img src="https://github.com/typst/webapp-issues/assets/7661193/a9dda5ba-4996-432e-8797-cf4505c959b7" width="200px">

![image](https://github.com/typst/webapp-issues/assets/7661193/80fc01fd-bb69-4728-a366-61e85b604821)

<img src="https://github.com/typst/webapp-issues/assets/7661193/06a925bc-e64f-4f21-ac6d-53a80d42788a" width="200px">

**Info:**
It seems to be purely client-side issue since the error message fires before any request is made.
- Mozilla Firefox 124.0.2
- Ubuntu 23.10; 6.5.0-27-generic

### Reproduction URL

https://typst.app/project/pycuZQ9uk1igMzFNEeHDKb

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
That's very strange, I cannot reproduce it. This happens for all of your projects?

**Comment by zouharvi** [comment]
Does not happen anymore for me. Did the webapp change or is the bug stochastic?

**Comment by laurmaedje** [comment]
I don't think anything related to this changed.

**Comment by Andrew15-5** [comment]
I faced this bug today when I wanted to port my local project file-by-file (isn't there an archive/dir upload?).

So basically I have an import in the main file of a file that I am creating.

1. Create a file (that is referenced)
2. Error shows up

I tried a couple of times and each time I got the same error. I have no idea what exactly triggers it.

<details><summary>screenshot</summary>

![image](https://github.com/typst/webapp-issues/assets/37143421/8ae3b5be-bea7-4db9-b2d5-3f65fc9f841f)

</details>

**Comment by laurmaedje** [comment]
My best guess is that the operation was somehow triggered twice. The first one suceeds and the second one fails (to no effect). Still can't reproduce this though.

**Comment by Andrew15-5** [comment]
Do you want a screen recording? Or just reproduce on your machine?

**Comment by laurmaedje** [comment]
If you have a reliable reproduction, a screen recording would be much appreciated.

**Comment by Andrew15-5** [comment]
I think something has changed, don't know if it's possible to reproduce the issue. But what I can say is that now I can't create files without an extension. Now by default it will always append `.typ` to the name. So if I create `a.typ` by writing `a.typ` or `a` and then try to create `a`, it will show that the file exists, because it implicitly added `.typ` again. This can be a related issue, or a new one. As a freedom enjoyer, I do not enjoy implicit stuff, especially if I'm just not allowed to use any extension or no extension at all.

If I create `a` file that is automatically named as `a.typ` and try to remove or change the extension, it won't let me.

**Comment by laurmaedje** [comment]
Adding a `.typ` extension is intentional behaviour and I think it should be left as-is. People will easily not know or forget to add the extension. You can create a plain file without extension via upload.

**Comment by Andrew15-5** [comment]
I know that it's intentional, but not being able to name it or rename it as I want is definitely not good. Using upload, i.e, other software is definitely a hack, there should be no hacks for naming a file. Furthermore, if I upload file `a` and then rename it to `aa` it will append `.txt` to it. And I can't change it to, for example, `.py`. For me, this is extremely limiting for such a basic action. But I guess there is already an issue for that: https://github.com/typst/webapp-issues/issues/244. And it also mentions the fact that you can't move files in the project structure. Though it's a bit outdated, since it talks about renaming files without any extension, which is now impossible to create without some hackery.
