### ISSUE TITLE
Support nightly/unreleased/in-dev version of Typst

### ISSUE THREAD

**Issue by bastienvoirin** [typst/webapp-issues#375]
### Description

Add a "Latest development version (commit #ABCDEF)" option to the "Compiler version" dropdown menu, with a warning modal to prompt users to 1) be mindful of the risks and 2) strongly encourage them to backup their projects.

### Use Case

- This would simplify (and even encourage) beta-testing of release candidates (AFAIK, Typst 0.11 RC were manually added and removed from the "Compiler version" menu).
- This would benefit people with tight deadlines (reports, briefs, presentations...) who would like to use the most up-to-date bug fixes and features.

**Comment by MDLC01** [comment]
I agree nightly versions would be great. Unless something goes terribly wrong, I don't think there is any risk with using an untested version of the compiler (apart from compilation failing, which is fine). However, I would advise against using a nightly version if you have a tight deadline, because your document could stop compiling at any point. AFAIK, each version does indeed need to be manually added to the webapp currently because manual tweaking is required.

**Comment by bastienvoirin** [comment]
> Latest commit is probably a bit overkill, but a nightly version would indeed be cool!

> I agree nightly versions would be great.

A nightly version would be sufficient indeed.

> I would advise against using a nightly version if you have a tight deadline, because your document could stop compiling at any point.

Assuming that the user has no backup (a legitimate assumption despite the warning modal), I agree.

**Comment by laurmaedje** [comment]
Available now:

![image](https://github.com/user-attachments/assets/8504c3f8-3705-4021-a3bf-6a1d5648026f)

It won't be updated every night since it's a manual process, but regularly.
