### ISSUE TITLE
Add Fontawesome fonts

### ISSUE THREAD

**Issue by mintyfrankie** [typst/webapp-issues#401]
### Description

Would it be possible to add [Fontawesome](https://fontawesome.com/download) to the font list on webapp?

### Use Case

It can be used seamlessly with the [fontawesome package](https://typst.app/universe/package/fontawesome/) and various templates (for example [brilliant-cv](https://typst.app/universe/package/brilliant-cv)), without the need to manually download and upload the fonts to the online editor.

**Comment by JamesxX** [comment]
Licensing looks like it would take a bunch of lawyers to figure out which plan Typst GmbH would need in order to serve it. Perhaps a more elegant and broader reaching solution would be an IDE integration for purchasing licenses to fonts? It shouldn't be in any way a priority but it would for sure make for a nice UX

**Comment by andreacfromtheapp** [comment]
> Licensing looks like it would take a bunch of lawyers to figure out which plan Typst GmbH would need in order to serve it. Perhaps a more elegant and broader reaching solution would be an IDE integration for purchasing licenses to fonts? It shouldn't be in any way a priority but it would for sure make for a nice UX

can I suggest to use open source alternatives to FA? Like BoxIcons v2?

https://v2.boxicons.com/?query=

whike on the topic, Bunny fonts also are great for non tracking fonts :) 

https://fonts.bunny.net/

cheers!

**Comment by laurmaedje** [comment]
@andreacfromtheapp Those fonts are a bit niche for inclusion in the web app, but you can of course just upload them into your project and start using them.

**Comment by andreacfromtheapp** [comment]
@laurmaedje you are of course ultimately deciding here, however: Bunny Fonts are Google Fonts without the bad parts. BoxIcons, I would agree.

thank you for Typst, it is brilliant and has me in awe!

**Comment by laurmaedje** [comment]
Yeah, I meant BoxIcons specifically. The plural was wrong. Thanks for the kind words!

**Comment by andreacfromtheapp** [comment]
No worries at all :)
ps: just thinking out loud here:
what if the Typst App were to include Fonts and Icons transparently directly from the UI/UX with a naming convention that users could refer to in their templates/docs? Or use as if they were “emojis” with a click of a button?
At the point it would not matter how popular the sources are. Because they would be native to the app. It would be a win-win situation.
Less imports and reliance on externals. No licensing nor lawyers. Less how-tos and error proneness for the dev and users. Etc.
Please don’t take this the wrong way, I just get excited about great projects and want to help.  
On Mon, Jun 23, 2025 at 11:11 AM, Laurenz ***@***.***&gt; wrote:    laurmaedje left a comment  (typst/webapp-issues#401)
 Yeah, I meant BoxIcons specifically. The plural was wrong. Thanks for the kind words! —

**Comment by laurmaedje** [comment]
I'm not sure I understand the proposal. Could you explain a bit more?

**Comment by andreacfromtheapp** [comment]
Sure! I will try to formulate something meaningful later tonight.
Mind that I have only found out about Typst last night and that so far I have only used it to make my CV with the brilliant template. I’ll do my best.
  
On Mon, Jun 23, 2025 at 11:40 AM, Laurenz ***@***.***&gt; wrote:    laurmaedje left a comment  (typst/webapp-issues#401)
 I'm not sure I understand the proposal. Could you explain a bit more? —

**Comment by andreacfromtheapp** [comment]
Hi, I haven’t forgot about this. I’ve been having connectivity issues since yesterday. I’m going to elaborate more in details ASAP.
For now, I don’t want to leave this hanging for long. Here’s a brief try.
I did have a look around Typst source code to understand how it handles fonts.
For typist-cli and typst standard library I see it scans locally for installed fonts and that has some predefined fonts. Here, it could be a matter of requiring (as an example) Nerd Fonts as a dependency. Need Fonts are a big bucket of web fonts that include many logos, for example. Many editors (like lazyvim) rely on this to make icons available in their “GUIs”. I understand this may not be ideal for Typst, but it’s exemplary of how it could be done. No need to install the whole NF catalog, usually a desired font from the nerd font would suffice. I.e: Sans Pro Nerd Font.
For the web app, it could be handled the same way but by relying on Bunny Fonts and Box Icons and by making the available the same way they are used right now. I see that templates use “LinkedIn”, “email”, “mobile”, and so forth and that the icons automatically are placed in the final document. I deduce there is a bit of code somewhere that is aware of these “codes”. It would be a matter of making icons available as you do with fonts.
I know this isn’t the best explanation and I’ll try harder as soon as my Internet issues are resolved.
I hope it helps.
  
On Mon, Jun 23, 2025 at 2:06 PM, Andrea C ***@***.***&gt; wrote:    andreacfromtheapp left a comment  (typst/webapp-issues#401)
 Sure! I will try to formulate something meaningful later tonight. 
 Mind that I have only found out about Typst last night and that so far I have only used it to make my CV with the brilliant template. I’ll do my best. 
 
 On Mon, Jun 23, 2025 at 11:40 AM, Laurenz ***@***.***&amp;gt; wrote: laurmaedje left a comment (typst/webapp-issues#401) 
 I'm not sure I understand the proposal. Could you explain a bit more? —
