### ISSUE TITLE
"There is a mismatch between file name and format" error when pushing to git repo

### ISSUE THREAD

**Issue by peng1999** [typst/webapp-issues#471]
### Description

After writing the commit message and click "push" button, the error occurs and refuse to proceed pushing.

This is the layout of the repo:
<img width="360" alt="image" src="https://github.com/user-attachments/assets/b915b2db-bdb2-4d20-bfca-494f7aec8535">

The `latex` folder is not used but I want to keep that. Is that cause a problem?

### Browsers

Firefox

### OS

macOS

**Comment by reknih** [comment]
This is now fixed in almost all cases. Previously, faulty logic prevented the move of file types not known to the web app. This is now resolved, see #244. It can still happen in rare edge cases (i.e. when a file that was UTF-8 decodable ceases to be). We are tracking this internally but since it should be now fixed for almost all cases, I'll close this issue.
